N01467577_PassionProject/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Diagnostics;
using N01467577_PassionProject.Models;
using N01467577_PassionProject.Models.ViewModels;
using System.Web.Script.Serialization;

namespace N01467577_PassionProject.Controllers
{
    public class CartController : Controller
    {
            private static readonly HttpClient client;
            private JavaScriptSerializer jss = new JavaScriptSerializer();

            static CartController()
            {
                client = new HttpClient();
                client.BaseAddress = new Uri("https://localhost:44374/api/");
            }
        private void GetApplicationCookie()
        {
            string token = "";
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;
            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);
            return;
        }
        public ActionResult List()
        {
            
            string url = "cartdata/listcarts";
            HttpResponseMessage response = client.GetAsync(url).Result;      
            IEnumerable<CartDto> Cart = response.Content.ReadAsAsync<IEnumerable<CartDto>>().Result;           
            return View(Cart);
        }

        // GET: Cart/Details/5
        public ActionResult Details(int id)
        {
           
            DetailsCart ViewModel = new DetailsCart();

            string url = "cartdata/findCart/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            Debug.WriteLine("The response code is ");
            Debug.WriteLine(response.StatusCode);
            CartDto SelectedCart = response.Content.ReadAsAsync<CartDto>().Result;
            Debug.WriteLine("Received : ");
            Debug.WriteLine(SelectedCart.CustomerName);
            ViewModel.SelectedCart = SelectedCart;
            url = "productdata/listproductsforCart/" + id;
            response = client.GetAsync(url).Result;
            IEnumerable<ProductDto> AddedItems = response.Content.ReadAsAsync<IEnumerable<ProductDto>>().Result;
            ViewModel.AddedItems = AddedItems;
            url = "productdata/ListProductsNotaddedtoCart/" + id;
            response = client.GetAsync(url).Result;
            IEnumerable<ProductDto> AvailableItems = response.Content.ReadAsAsync<IEnumerable<ProductDto>>().Result;
            ViewModel.AvailableItems = AvailableItems;
            return View(ViewModel);
        }
       
        [HttpGet]
        [Authorize]
        public ActionResult Remove(int id, int ProductId)
        {
            GetApplicationCookie();
            Debug.WriteLine("Attempting to unassociate  :" + id + " with Product: " + ProductId);        
            string url = "cartdata/RemoveProductfromCart/" + id + "/" + ProductId;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;            
            return RedirectToAction("Details/" + id);
        }

        public ActionResult Error()
        {

            return View();
        }
        [Authorize]
        // GET: Cart/New
        public ActionResult New()
        {
            return View();
        }
        [Authorize]
        // POST: Cart/Create
        [HttpPost]
        public ActionResult Create(Cart Cart)
        {
            GetApplicationCookie();
            Debug.WriteLine("the json payload is :");
            Debug.WriteLine(Cart.date);          
            string url = "cartdata/addcart";
            string jsonpayload = jss.Serialize(Cart);
            Debug.WriteLine(jsonpayload);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }


        }
        //POST: Cart/Add/{cartid}
        [HttpPost]
        [Authorize]
        public ActionResult Add(int id, int ProductId)
        {
            GetApplicationCookie();           
            string url = "cartdata/AddProducttoCart/" + id + "/" + ProductId;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;           
            return RedirectToAction("Details/" + id);
        }
        [Authorize]
        // GET: Cart/Edit/5
        public ActionResult Edit(int id)
        {
            string url = "Cartdata/findCart/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            CartDto selectedCart = response.Content.ReadAsAsync<CartDto>().Result;
            Debug.WriteLine(selectedCart.CustomerName);
            return View(selectedCart);
        }
        [Authorize]
        // POST: Cart/Update/5
        [HttpPost]
        public ActionResult Update(int id, Cart Cart)
        {
            GetApplicationCookie();
            string url = "Cartdata/updateCart/" + id;
            string jsonpayload = jss.Serialize(Cart);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(content);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        [Authorize]
        // GET: Cart/Delete/5
        public ActionResult DeleteConfirm(int id)
        {
            string url = "Cartdata/findCart/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            CartDto selectedCart = response.Content.ReadAsAsync<CartDto>().Result;
            return View(selectedCart);
        }
        [Authorize]
        // POST: Cart/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            GetApplicationCookie();
            string url = "Cartdata/deleteCart/" + id;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

N01467577_PassionProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Diagnostics;
using N01467577_PassionProject.Models;
using N01467577_PassionProject.Models.ViewModels;
using System.Web.Script.Serialization;

namespace N01467577_PassionProject.Controllers
{
    public class ProductController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        static ProductController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                UseCookies = false
            };

            client = new HttpClient(handler);
            client.BaseAddress = new Uri("https://localhost:44374/api/");
        }       
        private void GetApplicationCookie()
        {
            string token = "";
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;
            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;           
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);
            return;
        }

        // GET: Product/List  
        public ActionResult List()
        {         
            string url = "productdata/listproducts";
            HttpResponseMessage response = client.GetAsync(url).Result;          
            IEnumerable<ProductDto> p = response.Content.ReadAsAsync<IEnumerable<ProductDto>>().Result;          
            return View(p);
        }
        // GET: Product/UserViewProductPage 
        public ActionResult UserViewProductPage()
        {
            string url = "productdata/listproducts";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<ProductDto> p = response.Content.ReadAsAsync<IEnumerable<ProductDto>>().Result;
            return View(p);
        }
        // GET: product/Details/2
        public ActionResult Details(int id)
        {
            DetailsProduct ViewModel = new DetailsProduct();

            string url = "Productdata/findProduct/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            Debug.WriteLine("The response code is ");
            Debug.WriteLine(response.StatusCode);
            ProductDto SelectedProduct = response.Content.ReadAsAsync<ProductDto>().Result;
            Debug.WriteLine("Product received : ");
            Debug.WriteLine(SelectedProduct.ProductName);
            ViewModel.SelectedProduct = SelectedProduct;
            url = "cartdata/listcartsforproduct/" + id;
            response = client.GetAsync(url).Result;
            IEnumerable<CartDto> RelatedCart = response.Content.ReadAsAsync<IEnumerable<CartDto>>().Result;
            ViewModel.RelatedCart = RelatedCart;   
            return View(ViewModel);
        }
        // GET: product/CustomerProductDetailsView/2
        public ActionResult CustomerProductDetailsView(int id)
        {
            GetApplicationCookie();
            DetailsProduct ViewModel = new DetailsProduct();

            string url = "Productdata/findProduct/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            Debug.WriteLine("The response code is ");
            Debug.WriteLine(response.StatusCode);
            ProductDto SelectedProduct = response.Content.ReadAsAsync<ProductDto>().Result;
            Debug.WriteLine("Product received : ");
            Debug.WriteLine(SelectedProduct.ProductName);
            ViewModel.SelectedProduct = SelectedProduct;
            url = "cartdata/listcartsforproduct/" + id;
            response = client.GetAsync(url).Result;
            IEnumerable<CartDto> RelatedCart = response.Content.ReadAsAsync<IEnumerable<CartDto>>().Result;
            ViewModel.RelatedCart = RelatedCart;
            return View(ViewModel);
        }
        public ActionResult Error()
        {
            return View();        }

        // GET: Product/New
        [Authorize]
        public ActionResult New()
        {            
            return View();
        }
        // POST: Product/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Product p, HttpPostedFileBase ProductPic)
        {
            GetApplicationCookie();
            string url = "productdata/addproduct";
            Debug.WriteLine(p.Qty);
            string jsonpayload = jss.Serialize(p);          
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            Debug.WriteLine(jsonpayload);
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(ProductPic); Debug.WriteLine(jsonpayload);
          
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        // GET: Product/Edit/2
        [Authorize]
        public ActionResult Edit(int id)
        {            
            string url = "productdata/findproduct/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            ProductDto selectedProduct = response.Content.ReadAsAsync<ProductDto>().Result;
            return View(selectedProduct);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Update(int id, Product p, HttpPostedFileBase ProductPic)
        {
            GetApplicationCookie();
            string url = "productdata/updateproduct/" + id;
            string jsonpayload = jss.Serialize(p);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(ProductPic);Debug.WriteLine(jsonpayload);
            
            if (response.IsSuccessStatusCode && ProductPic != null)
            {
                url = "ProductData/UploadProductPic/" + id;                
                MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                HttpContent imagecontent = new StreamContent(ProductPic.InputStream);
                requestcontent.Add(imagecontent, "ProductPic", ProductPic.FileName);
                response = client.PostAsync(url, requestcontent).Result;

                return RedirectToAction("List");
            }
            else if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        // GET: Product/Delete/2
        [Authorize]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "productdata/findproduct/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            ProductDto selectedProduct = response.Content.ReadAsAsync<ProductDto>().Result;
            return View(selectedProduct);
        }
        // GET: Product/Delete/2
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            GetApplicationCookie();
            string url = "productdata/deleteproduct/" + id;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

N01467577_PassionProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ToneHealthCoach", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Carts", "List", "Cart")</li>
                    <li>@Html.ActionLink("Products", "List", "Product")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

N01467577_PassionProject/Views/Shared/_User.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Tone Health Coach - HTML Template | Home Style One</title>
    <!-- Stylesheets -->
    <link href="/assets/user/css/bootstrap.css" rel="stylesheet">
    <link href="/assets/user/plugins/revolution/css/settings.css" rel="stylesheet" type="text/css"><!-- REVOLUTION SETTINGS STYLES -->
    <link href="/assets/user/plugins/revolution/css/layers.css" rel="stylesheet" type="text/css"><!-- REVOLUTION LAYERS STYLES -->
    <link href="/assets/user/plugins/revolution/css/navigation.css" rel="stylesheet" type="text/css"><!-- REVOLUTION NAVIGATION STYLES -->
    <link href="/assets/user/css/style.css" rel="stylesheet">
    <link href="/assets/user/css/responsive.css" rel="stylesheet">
    <!--Favicon-->
    <link rel="shortcut icon" href="/assets/user/images/favicon.png" type="image/x-icon">
    <link rel="icon" href="/assets/user/images/favicon.png" type="image/x-icon">
    <!-- Responsive -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

</head>
<body>
    <header class="main-header">
        <!-- Header top -->
        <!-- End Header-Top -->
        <!-- Header-upper -->
        <div class="header-upper">
            <div class="auto-container">
                <div class="clearfix">
                    <div class="pull-left logo-outer">
                        <div class="logo"><a href="#"><img src="/assets/user/images/logo.png" alt="" title=""></a></div>
                    </div>
                    <div class="pull-right upper-right clearfix">
                        <!--Info Box-->
                        <div class="upper-column info-box">
                            <ul>
                                <li> <div class="icon-box"><span class="fa fa-clock-o"></span></div> <strong>Time</strong></li>
                                <li>10:00am to 6:00pm</li>
                            </ul>
                        </div>
                        <!--Info Box-->
                        <div class="upper-column info-box">
                            <ul>
                                <li><div class="icon-box"><span class="fa fa-envelope"></span></div> <strong>Email </strong></li>
                                <li>herbalife@gmail.com</li>
                            </ul>
                        </div>
                        <!--Info Box-->
                        <div class="upper-column info-box">
                            <ul>
                                <li><div class="icon-box"><span class="fa fa-map-marker"></span></div> <strong>Address </strong></li>
                                <li>Apple St, New Mexico, USA</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header Upper -->
        <!-- Header Lower -->
        <div class="header-lower">

            <div class="auto-container clearfix">
                <div class="nav-outer clearfix">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <ul class="navigation clearfix">
                                <li class="current">
                                    <a href="../Home/CustomerIndex">Home</a>

                                </li>
                                <li class="dropdown">
                                    <a href="#">About Us</a>
                                    <ul>
                                        <li><a href="#">Herbal Life</a></li>
                                        <li><a href="#">Our Science</a></li>

                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Balance Diet</a>

                                </li>

                                <li>
                                    <a href="/Product/UserViewProductPage">Our Products</a>

                                </li>

                                <li><a href="#">View Cart</a></li>
                                <li><a href="#">Logout</a></li>

                                <li><a href="#">LogIn</a></li>

                                </li>
                            </ul>
                        </div>
                    </nav>

                    <!-- Search box -->

                </div>
            </div>
        </div>
        <!--End Header Lower-->
        <!--Sticky Header-->
        <!--End Sticky Header-->
    </header>
    @RenderBody()
    <footer class="main-footer">
        <div class="auto-container">

            <!--Widgets Section-->
            <div class="widgets-section">
                <div class="row clearfix">
                    <!--Big Column-->
                    <div class="big-column col-md-6 col-sm-12 col-xs-12">
                        <div class="row clearfix">

                            <!--Footer Column-->
                            <div class="footer-column col-md-6 col-sm-6 col-xs-12">
                                <div class="footer-widget about-widget">
                                    <div class="footer-logo">
                                        <figure>
                                            <a href="#"><img src="/assets/user/images/footer-logo.png" alt=""></a>
                                        </figure>
                                    </div>
                                    <div class="widget-content">

                                        <ul class="contact-info">
                                            <li class="address">
                                                <span class="icon fa fa-map-marker"></span>
                                                Address: 121, Park Drive, Varick Str, New York, NY 10012, USA
                                            </li>
                                            <li>
                                                <span class="icon fa fa-volume-control-phone"></span>
                                                Phone: (123) 0200 12345
                                            </li>
                                            <li>
                                                <span class="icon fa fa-envelope"></span>
                                                Email: herblelife@gmail.com
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <!--Footer Column-->
                            <div class="footer-column col-md-6 col-sm-6 col-xs-12">
                                <div class="footer-widget links-widget">
                                    <h2>Quick Links</h2>
                                    <div class="widget-content">
                                        <div class="row clearfix">
                                            <div class="col-lg-12 col-md-6 col-sm-6 col-xs-12">
                                                <ul class="list">
                                                    <li><a href="#">About Us</a></li>
                                                    <li><a href="#">Balance Diet</a></li>
                                                    <li><a href="#">Our Science</a></li>
                                                    <li><a href="#">community</a></li>
                                                    <li><a href="#">fitness tip</a></li>

                                                </ul>
                                            </div>

                                        </div>
                                    </div>
                                </div>


                            </div>

                        </div>
                    </div>

                    <!--Big Column-->
                    <div class="big-column col-md-6 col-sm-12 col-xs-12">
                        <div class="row clearfix">

                            <!--Footer Column-->
                            <div class="footer-column col-md-12 col-sm-12 col-xs-12">
                                <div class="footer-widget posts-widget">
                                    <h2>About Us</h2>
                                    <div class="text">We are a global nutrition company that has helped people pursue a healthy, active life since 1980. Our nutrition, weight-management and personal care products are available exclusively through our more than 2.3 million independent Associates in more than 90 countries. We support the Herbalife Family Foundation (HFF) and its Casa Herbalife program to help bring good nutrition to children in need. We also sponsor world-class athletes, teams and events around the globe, including the LA Galaxy and FC Barcelona soccer clubs, as well as champions in more than 15 other sports. Our Mission is to change people?s lives by providing the best business opportunity in direct selling and the best nutrition and weight-management products in the world.</div>
                                </div>
                            </div>

                            <!--Footer Column-->

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--Footer Bottom-->
        <div class="footer-bottom">
            <div class="auto-container">
                <div class="copyright-text">
                    <h4>Copyrights &copy; 2021 All Rights Reserved</h4>
                </div>
            </div>
        </div>
    </footer>

    <div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>

    <script src="assets/user/js/jquery.js"></script>
    <!--Revolution Slider-->
    <script src="/assets/user/plugins/revolution/js/jquery.themepunch.revolution.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="/assets/user/plugins/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script src="assets/user/js/main-slider-script.js"></script>
    <script src="assets/user/js/bootstrap.min.js"></script>
    <script src="assets/user/js/jquery-ui.js"></script>
    <script src="assets/user/js/jquery.fancybox.js"></script>
    <script src="assets/user/js/owl.js"></script>
    <script src="assets/user/js/jquery.bootstrap-touchspin.js"></script>
    <script src="assets/user/js/wow.js"></script>
    <script src="assets/user/js/appear.js"></script>
    <script src="assets/user/js/script.js"></script>


    </div><!--End pagewrapper-->

    <div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>
</body>
</html>